-- EDISS Sea database schema
-- FIRST-TIME SETUP:
-- Run only this file on a fresh PostgreSQL database for the sea project.
-- This file creates all required tables, indexes, locations, and one default admin login.
--
-- All sea-backend tables are prefixed with "sea_" to allow sharing a database
-- with the air backend without conflicts.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS sea_profiles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  profile_code VARCHAR(30) UNIQUE,
  company_name VARCHAR(200) NOT NULL,
  address TEXT,
  city VARCHAR(100),
  state VARCHAR(100),
  country VARCHAR(100) DEFAULT 'India',
  phone VARCHAR(20),
  email VARCHAR(200),
  carn_number VARCHAR(30),
  customs_house_code VARCHAR(10),
  icegate_code VARCHAR(20),
  pan_number VARCHAR(16),
  user_prefix VARCHAR(20),
  consol_agent_id VARCHAR(30),
  user_email VARCHAR(200),
  agent_name TEXT,
  address1 TEXT,
  address2 TEXT,
  gstin VARCHAR(20),
  billing_company VARCHAR(200),
  billing_state VARCHAR(100),
  gst_rate DECIMAL(5, 2) DEFAULT 18,
  pan_for_invoice VARCHAR(16),
  air_igm_rate DECIMAL(10, 2),
  sea_consol_lcl_rate DECIMAL(10, 2),
  sea_consol_fcl_rate DECIMAL(10, 2),
  air_manifest_rate DECIMAL(10, 2),
  air_manifest_min_bill DECIMAL(10, 2),
  location_code VARCHAR(10),
  user_id UUID,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sea_users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  password_plain VARCHAR(255),
  full_name VARCHAR(200) NOT NULL,
  email VARCHAR(200),
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  profile_id UUID REFERENCES sea_profiles(id),
  customs_house_code VARCHAR(10),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sea_profiles_user_id_fk'
  ) THEN
    ALTER TABLE sea_profiles
      ADD CONSTRAINT sea_profiles_user_id_fk
      FOREIGN KEY (user_id) REFERENCES sea_users(id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sea_profiles_user_id_location_code_key'
  ) THEN
    ALTER TABLE sea_profiles
      ADD CONSTRAINT sea_profiles_user_id_location_code_key UNIQUE (user_id, location_code);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS sea_locations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  iata_code VARCHAR(10) UNIQUE NOT NULL,
  city_name VARCHAR(150) NOT NULL,
  customs_house_code VARCHAR(10) UNIQUE,
  country VARCHAR(100) DEFAULT 'India',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sea_user_locations (
  user_id UUID NOT NULL REFERENCES sea_users(id) ON DELETE CASCADE,
  location_id UUID NOT NULL REFERENCES sea_locations(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, location_id)
);

CREATE TABLE IF NOT EXISTS sea_file_control_numbers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  profile_id UUID REFERENCES sea_profiles(id),
  user_id UUID REFERENCES sea_users(id),
  location_code VARCHAR(10) NOT NULL,
  control_number INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sea_file_control_numbers_user_location
  ON sea_file_control_numbers (user_id, location_code)
  WHERE user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS sea_mbls (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  mbl_no VARCHAR(30) UNIQUE NOT NULL,
  mbl_date DATE,
  cargo_move VARCHAR(80),
  port_of_delivery VARCHAR(120),
  dest_cfs VARCHAR(120),
  subline_no VARCHAR(30),
  vessel_voyage_no VARCHAR(120),
  port_of_loading VARCHAR(120),
  port_of_unloading VARCHAR(120),
  cargo_nature VARCHAR(120),
  item_type VARCHAR(120),
  importer_name VARCHAR(200),
  importer_address1 TEXT,
  importer_address2 TEXT,
  importer_address3 TEXT,
  description TEXT,
  marks_numbers TEXT,
  transport VARCHAR(60),
  bond_no VARCHAR(60),
  carrier_name VARCHAR(200),
  carrier_code VARCHAR(60),
  mlo_name VARCHAR(200),
  mlo_code VARCHAR(60),
  total_packages INTEGER NOT NULL DEFAULT 0,
  total_gross_weight DECIMAL(12, 3) NOT NULL DEFAULT 0,
  total_volume_cbm DECIMAL(12, 3) NOT NULL DEFAULT 0,
  customs_house_code VARCHAR(10),
  profile_id UUID REFERENCES sea_profiles(id),
  created_by UUID REFERENCES sea_users(id),
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sea_mbls_created_by ON sea_mbls (created_by);
CREATE INDEX IF NOT EXISTS idx_sea_mbls_customs_house_code ON sea_mbls (customs_house_code);

CREATE TABLE IF NOT EXISTS sea_hbls (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  mbl_id UUID NOT NULL REFERENCES sea_mbls(id) ON DELETE CASCADE,
  hbl_no VARCHAR(30) UNIQUE NOT NULL,
  hbl_date DATE,
  container_no VARCHAR(40),
  seal_no VARCHAR(40),
  container_size VARCHAR(20),
  container_type VARCHAR(50),
  soc_flag VARCHAR(10),
  agent_code VARCHAR(40),
  package_count INTEGER NOT NULL DEFAULT 0,
  gross_weight DECIMAL(12, 3) NOT NULL DEFAULT 0,
  cargo_net_weight DECIMAL(12, 3) NOT NULL DEFAULT 0,
  volume_cbm DECIMAL(12, 3) NOT NULL DEFAULT 0,
  package_type VARCHAR(80),
  cargo_description TEXT,
  marks_numbers TEXT,
  hs_code VARCHAR(30),
  imo_code VARCHAR(30),
  item_type VARCHAR(120),
  invoice_value_currency VARCHAR(80),
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_by UUID REFERENCES sea_users(id),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sea_hbls_mbl_id_sort_order ON sea_hbls (mbl_id, sort_order, created_at);

CREATE TABLE IF NOT EXISTS sea_mlos (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  mlo_name VARCHAR(200) NOT NULL,
  mlo_code VARCHAR(60) NOT NULL,
  agent_code VARCHAR(40),
  created_by UUID REFERENCES sea_users(id),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sea_carriers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  carrier_name VARCHAR(200) NOT NULL,
  carrier_code VARCHAR(60),
  bond_number VARCHAR(60),
  transport VARCHAR(60),
  dest VARCHAR(120),
  address VARCHAR(35),
  description VARCHAR(150),
  created_by UUID REFERENCES sea_users(id),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sea_transmissions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  sea_mbl_id UUID REFERENCES sea_mbls(id) ON DELETE SET NULL,
  file_name VARCHAR(255) NOT NULL,
  file_content TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'placeholder',
  created_by UUID REFERENCES sea_users(id),
  created_at TIMESTAMP DEFAULT NOW()
);

-- New MBL columns (v2 form)
ALTER TABLE sea_mbls ADD COLUMN IF NOT EXISTS igm_no VARCHAR(30);
ALTER TABLE sea_mbls ADD COLUMN IF NOT EXISTS igm_date DATE;
ALTER TABLE sea_mbls ADD COLUMN IF NOT EXISTS vessel_date DATE;
ALTER TABLE sea_mbls ADD COLUMN IF NOT EXISTS vessel_code VARCHAR(30);
ALTER TABLE sea_mbls ADD COLUMN IF NOT EXISTS vessel_name VARCHAR(120);
ALTER TABLE sea_mbls ADD COLUMN IF NOT EXISTS line_no VARCHAR(30);
ALTER TABLE sea_mbls ADD COLUMN IF NOT EXISTS shipping_line VARCHAR(200);
ALTER TABLE sea_mbls ADD COLUMN IF NOT EXISTS imo_code VARCHAR(30);

-- New HBL columns (fields moved from MBL to HBL in v2 form)
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS cargo_move VARCHAR(80);
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS port_of_delivery VARCHAR(120);
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS dest_cfs VARCHAR(120);
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS subline_no VARCHAR(30);
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS cargo_nature VARCHAR(120);
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS importer_name VARCHAR(200);
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS importer_address1 TEXT;
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS importer_address2 TEXT;
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS importer_address3 TEXT;
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS carrier_name VARCHAR(200);
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS carrier_code VARCHAR(60);
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS bond_no VARCHAR(60);
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS transport VARCHAR(60);
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS mlo_name VARCHAR(200);
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS mlo_code VARCHAR(60);
ALTER TABLE sea_hbls ADD COLUMN IF NOT EXISTS containers_json JSONB;

INSERT INTO sea_locations (iata_code, city_name, customs_house_code, country) VALUES
  ('NSA1', 'Nhava Sheva Port', 'INNSA1', 'India'),
  ('PAV1', 'Pipavav Port', 'INPAV1', 'India'),
  ('MUN1', 'Mundra Port', 'INMUN1', 'India'),
  ('MAA1', 'Chennai Port', 'INMAA1', 'India'),
  ('COK1', 'Cochin Port', 'INCOK1', 'India'),
  ('CCU1', 'Kolkata Sea', 'INCCU1', 'India'),
  ('MRM1', 'Goa Port', 'INMRM1', 'India'),
  ('HZA1', 'Hazira Port', 'INHZA1', 'India'),
  ('NML1', 'Mangalore Port', 'INNML1', 'India'),
  ('TUT1', 'Tuticorin Port', 'INTUT1', 'India'),
  ('VTZ1', 'Vizag Port', 'INVTZ1', 'India'),
  ('IXY1', 'Kandla Port', 'INIXY1', 'India'),
  ('KAT1', 'Kattupalli Port', 'INKAT1', 'India'),
  ('KRI1', 'Krishnapatnam Port', 'INKRI1', 'India'),
  ('ENR1', 'Ennore Port', 'INENR1', 'India'),
  ('BOM1', 'Mumbai Customs', 'INBOM1', 'India')
ON CONFLICT (iata_code) DO NOTHING;

-- Default admin profile for first login
INSERT INTO sea_profiles (
  profile_code,
  company_name,
  city,
  state,
  country,
  customs_house_code,
  location_code,
  email
) VALUES (
  'SEAADMIN-INNSA1',
  'EDISS Sea Default Admin',
  'Navi Mumbai',
  'Maharashtra',
  'India',
  'INNSA1',
  'INNSA1',
  'admin@edisssea.in'
)
ON CONFLICT (profile_code) DO NOTHING;

-- Default first-time admin user
-- Username: admin
-- Password: SeaAdmin@2026!
INSERT INTO sea_users (
  username,
  password_hash,
  password_plain,
  full_name,
  email,
  role,
  profile_id,
  customs_house_code,
  is_active
)
SELECT
  'admin',
  '$2a$10$0G4PrZAdCxaEJu04UfAFWe3kz06.WeFWbBcGFmlJZuhbVNpzbOfDa',
  'SeaAdmin@2026!',
  'System Admin',
  'admin@edisssea.in',
  'master_admin',
  p.id,
  'INNSA1',
  TRUE
FROM sea_profiles p
WHERE p.profile_code = 'SEAADMIN-INNSA1'
ON CONFLICT (username) DO NOTHING;

-- Carrier code is optional (only carrier name is mandatory) — relax the NOT NULL
-- constraint left over from an earlier version of this table.
ALTER TABLE sea_carriers ALTER COLUMN carrier_code DROP NOT NULL;

-- Port master tables (v3): non-Indian loading ports and Indian delivery ports (ICD/CFS/SEZ)
-- used by the MBL/HBL entry form's port autocompletes. Seeded from the customs port master list;
-- new ports can be added at runtime via /sea-loading-ports and /sea-delivery-ports.
CREATE TABLE IF NOT EXISTS sea_loading_ports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  port_code VARCHAR(20) UNIQUE NOT NULL,
  port_name VARCHAR(200) NOT NULL DEFAULT '',
  created_by UUID REFERENCES sea_users(id),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sea_delivery_ports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  port_code VARCHAR(20) UNIQUE NOT NULL,
  port_name VARCHAR(200) NOT NULL DEFAULT '',
  created_by UUID REFERENCES sea_users(id),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Seed: non-Indian loading ports
INSERT INTO sea_loading_ports (port_code, port_name) VALUES
  ('AEKLF', 'KHOR FAKKAN'),
  ('NOLAR', 'LARVIK'),
  ('VNQNM', 'CHU LAI'),
  ('VNC8Q', 'CHU LAI'),
  ('OMSLL', 'SALALAH'),
  ('USPEF', 'PORT EVERGLADE'),
  ('USPEV', 'PORT EVERGLADES'),
  ('DKAAL', 'AALBORG'),
  ('IDPLM', 'PALEMBANG'),
  ('IDFTG', 'FUTONG'),
  ('CNMWN', 'MAWAN'),
  ('ITTRI', 'TERMINI IMERESE'),
  ('CRMOB', 'MOIN COSTA RICA'),
  ('MYBKI', 'KOTA KINABALU'),
  ('CNFAN', 'FANGCHENG'),
  ('ITGIT', 'GIOIA TAURO'),
  ('VNHPP', 'TAN CANG HIEP'),
  ('NOMSS', 'MOSS NORWAY'),
  ('CMDLA', 'DOUALA'),
  ('CNJGZ', 'JINGZHOU,CHINA'),
  ('CAPRR', 'PRINCE RUPERT'),
  ('PHCGY', 'CAGAYAN DE ORO'),
  ('IDPJG', 'PANJANG-LAMPUNG'),
  ('IDTPP', 'TG PRIOK'),
  ('IDBUN', 'BUATAN'),
  ('PTLIS', 'LISBON-LISBOA'),
  ('MXESE', 'ENSENADA'),
  ('TRDIL', 'DILISKELESI'),
  ('VNVUT', 'VUNG TAU'),
  ('BDCGP', 'CHATTOGRAM'),
  ('GBTEE', 'TEESPORT'),
  ('KRKAN', 'GWANGYANG'),
  ('CNDCB', 'DA CHAN BAY'),
  ('BRFOR', 'FORTALEZA'),
  ('KWSWK', 'SHUWAIKH'),
  ('VNITC', 'SP-ITC VIETNAM'),
  ('USTUQ', 'TURKEY'),
  ('MYLBH', 'LABUAN,HADJI'),
  ('MYLBU', 'LABUAN'),
  ('AEKHL', 'KHALIFA'),
  ('TRDRC', 'DERINCE'),
  ('JPFKY', 'HIROSHIMA'),
  ('BRPEC', 'PECEM'),
  ('DKKAL', 'KALUNDBORG'),
  ('JPOMZ', 'OMAEZAKI'),
  ('CNXTA', 'XINGTAN'),
  ('DERTD', 'ROTTERDAM GERMA'),
  ('CNRZH', 'RIZHAO'),
  ('DKFRC', 'FREDERICIA'),
  ('QAHMD', 'HAMAD, QATAR'),
  ('USNYC', 'NEW YORK'),
  ('CNXIN', 'XINHUI'),
  ('BRNAT', 'NATAL'),
  ('MYKUA', 'KUANTAN'),
  ('CNHFE', 'HEFEI'),
  ('DOCAU', 'CAUCEDO'),
  ('IDMAK', 'MAKASSAR'),
  ('PRSJU', 'SAN JUAN'),
  ('USATL', 'ATLANTA'),
  ('EGDAM', 'DAMIETTA'),
  ('JPHKT', 'HAKATA'),
  ('CHI', 'CHICAGO'),
  ('GBPRU', 'PORTBURY'),
  ('LTKLJ', 'KLAIPEDA'),
  ('NOOSL', 'OSLO'),
  ('ESGIJ', 'GIJON'),
  ('TNTUN', 'TUNIS'),
  ('PECLL', 'CALLAO'),
  ('GRHER', 'HERAKLION'),
  ('ZACPT', 'CAPE TOWN'),
  ('SADMN', 'DAMMAN'),
  ('CNMFG', 'MAFANG CHINA'),
  ('KRINC', 'INCHEON KOREA'),
  ('TWTPE', 'TAIPEI'),
  ('MATNG', 'TANGIER'),
  ('CNYIC', 'YICHANG'),
  ('GBJER', 'JERSEY'),
  ('CNYUY', 'YUEYANG'),
  ('FRDKK', 'DUNKERQUE'),
  ('PHSFS', 'SUBIC BAY'),
  ('ARBUE', 'BUENOS AIRES'),
  ('IDBTM', 'BATAM'),
  ('AUTSV', 'TOWNSVILLE'),
  ('HNPCR', 'PUERTO CORTES'),
  ('SNDKR', 'DAKAR'),
  ('CNGAS', 'GAOSHA'),
  ('CNTAG', 'TAICANG'),
  ('JPSMN', 'SAKAIMINETO'),
  ('PTBAN', 'LISBOA'),
  ('DKCSF', 'COPENHAGEN'),
  ('USMOB', 'MOBILE'),
  ('TRTEK', 'TEKIRDAG'),
  ('CNGUG', 'FUQING'),
  ('IEORK', 'CORK'),
  ('GHTEM', 'TEMA'),
  ('ITVDL', 'VADO LIGURE'),
  ('NOAES', 'AALESUND'),
  ('GEPTI', 'POTI, GEORGIA'),
  ('RUNVS', 'NOVOROSSIYSK'),
  ('SAJUB', 'JUBAIL'),
  ('CNCAN', 'GUANGZHOU'),
  ('CNWUC', 'WUCHONGKOU'),
  ('TRKMX', 'KUMPORT'),
  ('THSCS', 'SAHATHAI'),
  ('CNAQG', 'ANQING'),
  ('VNNGH', 'NGHI SON'),
  ('CNCIV', 'CIVET'),
  ('USSEA', 'SEATTLE'),
  ('MUPLU', 'PORT LOUIS'),
  ('ECGYE', 'GUAYAQUIL'),
  ('TERMAD', 'MARDAS TURKEY'),
  ('DJJIB', 'DJIBOUTI'),
  ('ITSAL', 'SALERNO'),
  ('JPMOJ', 'MOJI JAPAN'),
  ('GBIMM', 'IMMINGHAM'),
  ('CNWEI', 'WEIHAI'),
  ('PHDVO', 'DAVAO'),
  ('THSGZ', 'SONGKHLA'),
  ('MYSDK', 'SANDAKAN'),
  ('CNWUZ', 'WUZHOU'),
  ('UAODS', 'ODESSA UKRAINE'),
  ('CLVAP', 'VALPARAISO'),
  ('VNDAD', 'DA NANG'),
  ('KWKWI', 'KUWAIT'),
  ('ILASH', 'ASHDOD'),
  ('GRVOL', 'VOLOS'),
  ('NZTRG', 'TAURANGA'),
  ('ITVCE', 'VENICE ITALY'),
  ('CNCSX', 'CHANGSHA'),
  ('BGBOJ', 'BURGAS'),
  ('TRAMB', 'AMBARLI TURKEY'),
  ('HRRJK', 'RIJEKA'),
  ('TRYAR', 'YARIMCA'),
  ('RULED', 'PETERSBURG'),
  ('KHPNH', 'PHNOM PENH'),
  ('GBGRG', 'GRANGEMOUTH'),
  ('ESAGP', 'MALAGA'),
  ('AUADL', 'ADELAIDE'),
  ('NZAKL', 'AUCKLAND'),
  ('JPOSA', 'OSAKA'),
  ('FIRAU', 'RAUMA'),
  ('CNSDG', 'SHUIDONG'),
  ('MYTWU', 'TAWAU MALAYSIA'),
  ('MXVER', 'VERACRUZ'),
  ('UAILK', 'CHORNOMORSK'),
  ('LVRIX', 'RIGA'),
  ('CNGAY', 'GAOYAO'),
  ('LBBEY', 'BEIRUT'),
  ('PHMNL', 'MANILA'),
  ('VNTCT', 'CAI MEP'),
  ('TRISK', 'ISKENDERUN'),
  ('CNLUU', 'LELIU'),
  ('JPMIZ', 'MIZUSHIMA'),
  ('COCTG', 'CARTAGENA'),
  ('BEZEE', 'ZEEBRUGGE'),
  ('BRITJ', 'ITAJAI BRAZIL'),
  ('BRSSA', 'SALVADOR'),
  ('VNSGN', 'HOCHI MINH CITY'),
  ('CHSCH', 'SCHAFFHAUSEN'),
  ('MXATM', 'ALTAMIRA'),
  ('BRVIX', 'VITORIA'),
  ('SEGOT', 'GOTEBORG'),
  ('ESMPG', 'MARIN'),
  ('AUBNE', 'BRISBANE'),
  ('ITNPO', 'NAPLES, NAPOLI'),
  ('IDBLW', 'BELAWAN'),
  ('VNCMT', 'CAI MEP'),
  ('VNTOT', 'CAI MEP'),
  ('ARZAE', 'ZARATE'),
  ('SESTO', 'STOCKHOLM'),
  ('ITTPS', 'TRAPANI'),
  ('BRIOA', 'ITAPOA'),
  ('IRBND', 'BANDAR ABBAS'),
  ('TNSFA', 'SFAX'),
  ('CNZAP', 'ZHAPU'),
  ('SEPIT', 'PITEA'),
  ('AUSYD', 'SYDNEY AUSTRALIA'),
  ('CNYZH', 'YANGZHOU'),
  ('TRALI', 'ALIAGA'),
  ('OMSOH', 'SOHAR'),
  ('ITCVV', 'CIVITAVECCHIA'),
  ('FIHEL', 'HELSINKI'),
  ('FIKTK', 'KOTKA'),
  ('MYBTU', 'BINTULU, MALAYSIA'),
  ('VNCLI', 'CAT LAI'),
  ('CNWNZ', 'WENZHOU'),
  ('BHBAH', 'BAHRAIN'),
  ('SAJED', 'JEDDAH'),
  ('AEJEA', 'JEBEL ALI'),
  ('ITRAN', 'RAVENNA'),
  ('MXZLO', 'MANZANILLO'),
  ('AULIV', 'LIVERPOOL'),
  ('GBSSH', 'SOUTH SHIELDS'),
  ('CNSIN', 'SHATIAN'),
  ('IDTPK', 'TAPAKTUAN SUMATRA'),
  ('BRSSZ', 'SANTOS'),
  ('CNYNF', 'YUNFU'),
  ('BRRIG', 'RIO GRANDE'),
  ('USTIW', 'TACOMA'),
  ('ITBRI', 'BARI, ITALY'),
  ('CNJIA', 'JIANGYIN'),
  ('PHCEB', 'CEBU PHILIPPINES'),
  ('TZDAR', 'DAR ES SALAAM TANZANIA'),
  ('EGALY', 'ALEXANDRIA'),
  ('DKCPH', 'KOBENHAVN'),
  ('MYPGU', 'PASIR GUDANG'),
  ('USNEW', 'NEW ORLEANS'),
  ('EGPSD', 'PORT SAID EG'),
  ('ROCND', 'CONSTANTA'),
  ('CAMTR', 'MONTREAL CANADA'),
  ('DEWVN', 'WILHELMSHAVEN GERMANY'),
  ('CNQIN', 'QINHUANGDAO'),
  ('MYPKG', 'PORT KLANG MALAYSIA'),
  ('MYKEL', 'KELANG MALAYSIA'),
  ('CNYTN', 'YANTIAN'),
  ('KRPUS', 'BUSAN KOREA'),
  ('SGSIN', 'SINGAPORE'),
  ('TRGEM', 'GEMLIK TURKEY'),
  ('CNXMN', 'XIAMEN'),
  ('ITBSN', 'BUSANA'),
  ('USNYK', 'NEW YORK'),
  ('CNNGB', 'NINGBO'),
  ('NLRTM', 'ROTTERDAM NETHERLAND'),
  ('THLCH', 'LAEM CHABANG THAILAND'),
  ('HKHKG', 'HONG KONG'),
  ('CNSHK', 'SHEKOU'),
  ('ITGOA', 'GENOA'),
  ('CNXGG', 'XINGANG'),
  ('VNHAN', 'HANOI'),
  ('VNHPH', 'HAIPHONG'),
  ('CNTAO', 'QINGDAO'),
  ('CNROQ', 'RONGQI'),
  ('CNZHA', 'ZHANJIANG'),
  ('CNNSA', 'NANSHA'),
  ('MYTPP', 'TANJUNG PELEPAS'),
  ('CNYQS', 'BEIJIAO'),
  ('CNZSN', 'ZHONGSHAN'),
  ('USSAV', 'SAVANNAH'),
  ('CNHUA', 'HUANGPU'),
  ('TRIZM', 'IZMIR'),
  ('GBFXT', 'FELIXSTOWE'),
  ('PLGDY', 'GDYNIA'),
  ('MYPEN', 'PENANG MALAYSIA'),
  ('IDJKT', 'JAKARTA'),
  ('USHQN', 'HOUSTON'),
  ('DEHAM', 'HAMBURG GERMANY'),
  ('IDSRG', 'SEMARANG'),
  ('PKBQM', 'PORT QASIM'),
  ('AUFRE', 'FREMANTLE'),
  ('AUMEL', 'MELBOURNE'),
  ('AROES', 'SAN ANTONIO OESTE'),
  ('AEAUH', 'ABU DHABI'),
  ('CNJMN', 'JIANGMEN'),
  ('PLGDN', 'GDANSK'),
  ('CNSZX', 'SHENZHEN DA CHAN BAY'),
  ('LKCMB', 'COLOMBO LK'),
  ('SIKOP', 'KOPER'),
  ('TWKEL', 'KEELUNG TAIWAN'),
  ('CNDLC', 'DALIAN'),
  ('CNZJG', 'ZHANGJIAGANG'),
  ('CNWHI', 'WUHU CHINA'),
  ('CLLSQ', 'LOS ANGELES'),
  ('CNSWA', 'SHANTOU'),
  ('CNSHA', 'SHANGHAI'),
  ('JPUKB', 'KOBE'),
  ('CNFOC', 'FUZHOU'),
  ('CNTSN', 'TIANJIN')
ON CONFLICT (port_code) DO NOTHING;

-- Seed: Indian delivery ports (ICD/CFS/SEZ)
INSERT INTO sea_delivery_ports (port_code, port_name) VALUES
  ('INTUI6', 'KESAVARAM SEZ'),
  ('INJKA6', 'SACHANA'),
  ('INDNK6', 'ICD DHANAKYA'),
  ('INJSG6', 'ICD JHARSUGUDA'),
  ('INGPL6', 'AHMEDGARH'),
  ('NPBRA', 'BIRATNAGAR'),
  ('INPYS6', 'SIPCOT-SEZ/EROD'),
  ('INCJO6', 'SIPCOT LITD'),
  ('INMAQ6', 'MANGALORE SEZ'),
  ('INAKB6', 'BRANDIX SEZ'),
  ('INJJK6', 'ICD JAJPUR'),
  ('INAIP6', 'ICBPPL SEZ/EDAY'),
  ('NPBBI', 'BHAIRAHAWA'),
  ('INBOM6', 'ANDHERI SEEPZ'),
  ('INWDH6', 'ICD MORBI'),
  ('INCBS6', 'SYNEFRA E&C LTD'),
  ('INSPE6', 'APACHE SEZ'),
  ('INVGR6', 'ICD VIRAMGAM'),
  ('INVRM6', 'ICD VARNAMA'),
  ('INPJN6', 'JNPA SEZ'),
  ('INLPS6', 'DSIL SEZ/RANGA'),
  ('INDLB6', 'DAULATABAD ICD'),
  ('INGRW6', 'CHAKAN'),
  ('INRUG6', 'ICD BARHI'),
  ('INHST6', 'KIADB SEZ'),
  ('NPBRG', 'BIRGANJ NEPAL'),
  ('INAKR6', 'SEZ/VISAKHAPATN'),
  ('INTMI6', 'IFFCO KISAN,SEZ'),
  ('INKQZ6', 'SATTVA BLR ICD'),
  ('INPNQ6', 'HADAPSAR,SEZ,PU'),
  ('INNPK6', 'NANDIAMBAKKAM'),
  ('INCJS6', 'SEZ SIPCOT HI'),
  ('INVZM6', 'VIZAG SEZ'),
  ('INCJD6', 'DLF INFO CITY'),
  ('INVLR6', 'SIPC SEZ/VELLOR'),
  ('INJHV6', 'VISHAKHAPATNAM'),
  ('INVZR6', 'REDDY-R-SEZ'),
  ('BTTHI', 'BHUTAN THIMPU'),
  ('INCOK6', 'COCHIN (EPZ/SEZ'),
  ('INTEN6', 'SIPCOT SEZ'),
  ('INGLY6', 'APIICL?SEZ'),
  ('INSBC6', 'BIOCON SEZ'),
  ('INGNC6', 'GIFT SEZ LTD'),
  ('INQRP6', 'ICD KILA RAIPUR'),
  ('INPUI6', 'SEZ KRC INFRAS.'),
  ('INGIN6', 'KANDLA'),
  ('INLPB6', 'HYDERABAD SEZ'),
  ('INPAO6', 'SEZ PANOLI'),
  ('INBHD6', 'DAHEJ SEZ'),
  ('INKPK6', 'ICD MIHAN'),
  ('INMUZ6', 'MODINAGAR'),
  ('INMAA6', 'MEPZ SEZ'),
  ('INRML6', 'NAYA RAIPUR CON'),
  ('INKZT6', 'ELECTRONICS SEZ'),
  ('INNYP6', 'NAIDUPET SEZ'),
  ('INKJR6', 'MANAHATTAN SEZ'),
  ('INPNU6', 'MANJRI STUD'),
  ('INPNB6', 'SEZ PUNE'),
  ('INUDI6', 'ASPEN SEZ'),
  ('INAWM6', 'AURANGABAD'),
  ('INBNX6', 'CANDOR KOLKATA'),
  ('INNDA6', 'NOIDA SEZ'),
  ('INSCH6', 'SAP-SEZ/SURAT'),
  ('INSJR6', 'ICD SURAJPUR'),
  ('INHEM6', 'MANYATA EBP SEZ'),
  ('INPUE6', 'EON2'),
  ('INVTZ6', 'VISHAKHAPATNAM SEZ'),
  ('INBMA6', 'SEZ'),
  ('INCGL6', 'MWCDL AUTO ANCILLARIES'),
  ('INTAS6', 'SRICITY SEZ'),
  ('INGGU6', 'Unitech Reality Projects Limited'),
  ('INCCP6', 'PUNE EMBASSY PROJECT PVT LTD'),
  ('INAIG6', 'GIGAPLEX ESTATE PVT.LTD'),
  ('INIDR6', 'Vaishnav yard'),
  ('INCGA6', 'Mahindra World city Developers Limited'),
  ('BTPBH', 'BHUTAN'),
  ('INSTV6', 'SEZ SACHIN SURAT'),
  ('INHPI6', 'ICD KASHIPUR'),
  ('INVKH6', 'HIRANANDANI'),
  ('INAJM6', 'Mundra Port SEZ'),
  ('NPKTM', 'KATHMANDU'),
  ('INPNV6', 'ARSHIYA FTWZ'),
  ('INDEH6', 'HCL SEZ/Noida'),
  ('INAWW6', 'WIDL SEZ/Aurangabad'),
  ('INPEK6', 'EKIPL SEZ/Pune'),
  ('INBGQ6', 'AEQUS SEZ'),
  ('INLPJ6', 'JAMNAGAR SEZ'),
  ('INBHT6', 'DAHEJ SEZ'),
  ('INKDL6', 'KANDLA SEZ'),
  ('INMPR6', 'MALANPUR'),
  ('INCJJ6', 'J. Matadee Chennai Free Trade Zone'),
  ('INGWL6', 'Malanpur Gwalior'),
  ('INPWL6', 'ICD Palwal'),
  ('INDWN6', 'ICD Jattipur'),
  ('INDDL6', 'ICD (PSWC) Dhandari Kalan'),
  ('INSGF6', 'ICD (GRFL)Sahnewal Ludhiana'),
  ('INHDD6', 'ICD Pantnagar'),
  ('INPRK6', 'ICD Powarkheda'),
  ('INBOK6', 'ICD Borkhedi'),
  ('INHIR6', 'ICD Surat Hira Bourse'),
  ('INBAW6', 'ICD Bawal'),
  ('INJIGB', 'LCS Jaigaon'),
  ('INAIK6', 'ICD Khurja'),
  ('INSAJ6', 'ICD TUMB'),
  ('INNGB6', 'ICD BUTIBORI'),
  ('INCML6', 'ICD KHATUWAS'),
  ('INCPR6', 'ICD CHAWAPAYAL'),
  ('INBDI6', 'ICD BADDI'),
  ('INPNY6', 'ICD PULICHAPALLAM'),
  ('INSNI6', 'KANECH ICD/SAHNEWAL'),
  ('INHSU6', 'ICD Hosur'),
  ('INBDM6', 'SONIPAT ICD'),
  ('INDHA6', 'ICD DHANNAD'),
  ('INBNG6', 'ICD Tarapur'),
  ('INCHJ6', 'ICD Wardha'),
  ('INRTM6', 'ICD Ratlam'),
  ('INSKD6', 'ICD KALINGANAGAR'),
  ('INPKR6', 'ICD Pali Rewari'),
  ('INPMP6', 'ICD Pimpri'),
  ('INJBNB', 'LCS Jogbani'),
  ('INATRB', 'LCS Attari Road'),
  ('INTMX6', 'ICD Thimmapur'),
  ('INAMG6', 'ICD Amingaon'),
  ('INKBC6', 'ICD KRIBHCO Surat'),
  ('INTCR6', 'Thrissur ICD'),
  ('INDUR6', 'ICD Durgapur'),
  ('INTVT6', 'ICD Tondiapet'),
  ('INKYM6', 'ICD kottayam'),
  ('INBFR6', 'ICD Piyala'),
  ('INPNK6', 'ICD Panki'),
  ('INASR6', 'ICD Cheherta'),
  ('INJUC6', 'ICD Jalandhar'),
  ('INAKV6', 'ICD Ankaleshwar'),
  ('INSAC6', 'ICD Sachin'),
  ('INBVC6', 'ICD Faridabad(Sec'),
  ('INGNR6', 'ICD Marripalaem(Leap Intl. Ltd.)'),
  ('INILP6', 'ICD Irungattukottai Sriperumbudur'),
  ('INKAR6', 'ICD karur'),
  ('INAJJ6', 'ICD Arakkanom'),
  ('INSAU6', 'ICD Thar Dry Port sanand'),
  ('INLON6', 'ICD Loni'),
  ('INRAI6', 'ICD Raipur'),
  ('INMDD6', 'ICD Mandideep'),
  ('INPNP6', 'ICD Panipat'),
  ('INBSL6', 'ICD Bhusswal'),
  ('INKTT6', 'ICD Kota'),
  ('INCCH6', 'ICD Chinchwad Pune'),
  ('INTLG6', 'ICD Talegaon Pune'),
  ('INDIG6', 'ICD Dighi'),
  ('INJNR6', 'ICD Janori'),
  ('INNSK6', 'CSF Nashik'),
  ('INBLJ6', 'ICD Agra'),
  ('INVPI6', 'ICD VALSAD VAPI'),
  ('INMBD6', 'ICD Pakwara Moradabad'),
  ('INNGP6', 'ICD Nagpur'),
  ('INBRC6', 'ICD Dashrath Badodra'),
  ('INBHL6', 'ICD Bhilwara'),
  ('INTHA6', 'ICD Thar Dry Port Jodhpur'),
  ('INJUX6', 'ICD RAJSICO Basni Jodhpur'),
  ('INBWD6', 'ICD Bhiwadi'),
  ('INBGK6', 'ICD concor Jodhpur'),
  ('INPTL6', 'ICD Patli'),
  ('INGHR6', 'ICD Gari Harasaru'),
  ('INCPC6', 'ICD Chakeri Kanpur'),
  ('INKNU6', 'ICD JRY Kanpur'),
  ('INREA6', 'ICD Rewari'),
  ('INKKU6', 'ICD Concor Kanakpura Jaipur'),
  ('INTHO6', 'ICD Veerappandi'),
  ('INIGU6', 'ICD Irugur'),
  ('INTUP6', 'ICD Tirupur/Paakiyapalayam'),
  ('INCHE6', 'ICD Chettipalayam (Tirpur)'),
  ('INTDE6', 'ICD Thudiyalur'),
  ('INSLL6', 'ICD Singanallur'),
  ('INWAL6', 'ICD Waluj Aurangabad'),
  ('INMWA6', 'ICD Maliwada'),
  ('INRXLB', 'LCS Raxaul'),
  ('INPTPB', 'LCS Pertapole'),
  ('INMUL6', 'CFS Mulund'),
  ('INWFD6', 'ICD Banglore'),
  ('INAMD6', 'ACC AHMEDABAD'),
  ('INTKD6', 'ICD TUGHLAKABAD'),
  ('INTUT6', 'ICD Tuticorin'),
  ('ININD6', 'ICD Pitampur'),
  ('INSBI6', 'ICD Sabarmati Ahmedabad'),
  ('INSNF6', 'ICD Hyderabad'),
  ('INLDH6', 'ICD Ludhiana'),
  ('INPPG6', 'ICD Patparganj'),
  ('INJAI6', 'ICD Jaipur'),
  ('INFBD6', 'ICD FARIDABAD'),
  ('INDER6', 'CONCOR DADRI'),
  ('INCPL6', 'CGM DADARI'),
  ('INTTP6', 'TRIDENT'),
  ('INSTT6', 'CFS STARTRACK DADARI'),
  ('INAPL6', 'Albatross Inland Ports Dadri'),
  ('INVTZ1', 'Vizag'),
  ('INTUT1', 'Tuticorin'),
  ('INPNY1', 'Pondicherry Custom House'),
  ('INPAV1', 'Pipavav'),
  ('INPRT1', 'Paradeep Port'),
  ('INNSA1', 'Nhava Sheva'),
  ('INNPT1', 'Nagapattinam Custom House'),
  ('INMUN1', 'Mundra'),
  ('INBOM1', 'Mumbai Custom House'),
  ('INNML1', 'Mangalore'),
  ('INMDA1', 'Magdala port'),
  ('INKRI1', 'Krishnapatnam Port'),
  ('INKUK1', 'Kollam Port'),
  ('INCCU1', 'Kolkata Sea'),
  ('INKAT1', 'Kattupalli Port'),
  ('INIXY1', 'Kandla'),
  ('INKRK1', 'Karaikal SEA Port'),
  ('INKAK1', 'Kakinada'),
  ('INHZA1', 'Hazira Port Surat'),
  ('INMRM1', 'Goa Port'),
  ('INGGV1', 'Gangavaram Port'),
  ('INENR1', 'ENNORE PORT'),
  ('INDMT1', 'Dharmatar Port Mumbai'),
  ('INDMA1', 'Dhamra Port'),
  ('INDAH1', 'Dahej Port'),
  ('INCOK1', 'Cochin'),
  ('INMAA1', 'Chennai'),
  ('INBHU1', 'Bhavnagar'),
  ('INALA1', 'Alang')
ON CONFLICT (port_code) DO NOTHING;
